apiVersion: v1
kind: Pod
metadata:
  name: test-block
spec:
  containers:
    - name: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: csi-data-viettelplugin
  volumes:
    - name: csi-data-viettelplugin
      persistentVolumeClaim:
        claimName: csi-pvc-viettelplugin
