apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-viettelplugin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: csi-sc-viettelplugin