apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-demo
spec:
  volumeSnapshotClassName: csi-viettel-snapclass
  source:
    persistentVolumeClaimName: csi-pvc-viettelplugin